# Permalinks
permalink:           pretty

# Setup
title:               Matt Barnes
tagline:             "Data and not enough dogs"
url:                 http://msbarnes.github.io
baseurl:             ""
permalink: 	     /:year/:month/:day/:title/
pagination: 100
highlighter: rouge



# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Matt Barnes
  url:               https://twitter.com/msbarnes16
  email:             matthew.barnes16@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/msbarnes

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-sitemap
  - jekyll-redirect-from

#Markdown settings
kramdown:
  auto_ids: false
  enable_coderay: false
  entity_output: as_char
  footnote_nr: 1
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  toc_levels: 1..6 

#Exclude these files
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
 
